spring.application.name=ecom-app



#H2 provides a web interface called the H2 Console.
spring.h2.console.enabled=true





# This tells Spring Boot:
# Use the H2 database, and store it in memory.
# What does "in-memory" mean?
#
# The database exists only while your application is running.
#
# Start Spring Boot
# │
# ▼
# Create database in RAM
# │
# ▼
# Store data
# │
# ▼
# Stop application
# │
# ▼
# Everything is deleted
spring.datasource.url=jdbc:h2:mem:test



#This tells Hibernate:
#Print every SQL query it executes to the console.
spring.jpa.show-sql=true


#Every time your application starts:
#Drops existing tables.
#Creates new tables from your entity classes.
spring.jpa.hibernate.ddl-auto=create
